package fr.bebedlastreat.endoskullnpc.utils;

import fr.endoskull.api.commons.lang.MessageUtils;

public enum LobbyMessage implements MessageUtils {
    RED, GREEN, BLUE, CLICK_SKIP, PEARL_COLOR, BOOSTER9, BOOSTER8, BOOSTER7,
    BOOSTER6, BOOSTER5, BOOSTER4, BOOSTER3, BOOSTER2, BOOSTER1, BOOSTER0, DOUBLE, VIP, HERO,
    ULTIME, BOOST3, BOOST2, BOOST1, COINS5, COINS4, COINS3, COINS2, COINS1, FLY_ENABLE, FLY_DISABLE,
    GUI_BOX_ULTIME, GUI_BOX_VOTE, PROBABILITY, BOX_OPEN, ULTIME_AMOUNT, NEED_ULTIME_KEY, ULTIME_ALREADY_OPENING,
    ULTIME_BROADCAST, VOTE_AMOUNT, NEED_VOTE_KEY, VOTE_REWARD, GUI_FRIENDS, NO_FRIEND, GUI_MAIN_MENU,
    PVPKIT_DESC, BEDWARS_DESC, GUI_PROFILE, SETTINGS, FRIENDS, FRIENDS_REQUESTS, STATS, GUI_STATS,
    IDENTITY, IDENTITY_DESC, DATE, DATE_DESC, STAT_PVPKIT, JOIN_MESSAGE, PARKOUR_CHECKPOINT_ITEM,
    PARKOUR_RESET_ITEM, PARKOUR_LEAVE_ITEM, PARKOUR_RESTART, PARKOUR_FINISH, PARKOUR_FINISH_BEST, PARKOUR_FINISH_FIRST,
    PARKOUR_CHECKPOINT, PARKOUR_START, PARKOUR_FLY, PARKOUR_TELEPORT, PARKOUR_MOUNT, LOBBY_TITLE, LOBBY_MESSAGE, SHOP_ITEM,
    PROFILE_ITEM, MENU_ITEM, COSMETICS_ITEM, PEARL_RIDER, SCOREBOARD, LANGUAGE, GUI_LANGUAGE, LANGUAGE_CHANGE;

    private final static String path = "lobby";

    @Override
    public String getPath() {
        return path + "." + this.toString().toLowerCase().replace("_", "-");
    }
}
